name: ant
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/maxim-lobanov/runner-test-repo.git .
      - run: |
          ant -version
          ant -buildfile ant/build.xml
