name: go
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/maxim-lobanov/runner-test-repo.git .
      - run: |
          cd go/go-web-app
          go get -d
      - run: |
          cd go/go-web-app
          go build
