name: kotlin
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: git clone https://github.com/maxim-lobanov/runner-test-repo.git .
    - run: |
        cd kotlin/sample
        kotlinc App.kt -include-runtime -d App.jar
        java -jar App.jar
