name: nvm
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/maxim-lobanov/runner-test-repo.git .
      - run: |
          cd node
          npm config delete prefix
          . ~/.nvm/nvm.sh
          nvm use 14
          npm install
          npm start
