name: python
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/maxim-lobanov/runner-test-repo.git .
      - run: |
          python python/simple_app.py
      - run: |
          pipx --version
          pipx install pycowsay
          pycowsay hello