name: ruby
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/maxim-lobanov/runner-test-repo.git .
      - run: |
          cd ruby
          gem install bundler --force
          bundle install --retry=3 --jobs=4
          ruby ruby_version.rb
      - run: |
          cd ruby/cucumber-hello
          bundle install
          bundle exec cucumber

      - run: |
          ruby -ropenssl -e "puts 'Ruby SSL OK'"
          ruby -rreadline -e "puts 'Ruby readline OK'"